/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { AppointmentResponseDtoStatus } from './appointmentResponseDtoStatus';
import type { AppointmentPatientDto } from './appointmentPatientDto';
import type { AppointmentDoctorDto } from './appointmentDoctorDto';
import type { AppointmentMedicalRecordDto } from './appointmentMedicalRecordDto';

export interface AppointmentResponseDto {
  /** ID unik appointment */
  id: number;
  /** ID Pasien */
  patient_id: number;
  /** ID Dokter */
  doctor_id: number;
  /** Status appointment saat ini */
  status: AppointmentResponseDtoStatus;
  /** Tanggal kunjungan */
  tanggal_janji: string;
  /** Jam kunjungan */
  jam_janji: string;
  /** Keluhan awal saat mendaftar */
  keluhan?: string;
  created_at: string;
  updated_at: string;
  patient?: AppointmentPatientDto;
  doctor?: AppointmentDoctorDto;
  medical_record?: AppointmentMedicalRecordDto;
}
