/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

/**
 * Objective (Pemeriksaan Fisik)
 */
export type AppointmentMedicalRecordDtoObjektif = { [key: string]: unknown };
