/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export interface AppointmentPatientDto {
  id: string;
  nama_lengkap: string;
  nomor_rekam_medis: string;
  nik?: string;
  is_active?: boolean;
  email?: string;
  nomor_telepon?: string;
}
