/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { AppointmentMedicalRecordDtoSubjektif } from './appointmentMedicalRecordDtoSubjektif';
import type { AppointmentMedicalRecordDtoObjektif } from './appointmentMedicalRecordDtoObjektif';
import type { AppointmentMedicalRecordDtoAssessment } from './appointmentMedicalRecordDtoAssessment';
import type { AppointmentMedicalRecordDtoPlan } from './appointmentMedicalRecordDtoPlan';

export interface AppointmentMedicalRecordDto {
  id: string;
  appointment_id: string;
  /** Subjective (Keluhan Pasien) */
  subjektif?: AppointmentMedicalRecordDtoSubjektif;
  /** Objective (Pemeriksaan Fisik) */
  objektif?: AppointmentMedicalRecordDtoObjektif;
  /** Assessment (Diagnosa) */
  assessment?: AppointmentMedicalRecordDtoAssessment;
  /** Plan (Rencana Pengobatan) */
  plan?: AppointmentMedicalRecordDtoPlan;
  created_at: string;
  updated_at: string;
}
