/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export interface CheckActivationStatusResponseDto {
  /** Apakah user dapat meminta aktivasi */
  canActivate: boolean;
  /** Apakah akun sudah aktif */
  isActive: boolean;
  /** Apakah user memiliki email */
  hasEmail: boolean;
  message: string;
}
