/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export interface CreateMedicalRecordTreatmentDto {
  /** ID Rekam Medis */
  medicalRecordId: string;
  /** ID Perawatan */
  treatmentId: string;
  /**
   * Jumlah perawatan
   * @minimum 1
   */
  jumlah: number;
  /**
   * Harga satuan perawatan
   * @minimum 0
   */
  hargaSatuan: number;
  /**
   * Diskon untuk perawatan
   * @minimum 0
   */
  diskon?: number;
  /** Keterangan tambahan */
  keterangan?: string;
}
