/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

/**
 * Metode pembayaran
 */
export type CreatePaymentDtoMetodePembayaran = typeof CreatePaymentDtoMetodePembayaran[keyof typeof CreatePaymentDtoMetodePembayaran];


export const CreatePaymentDtoMetodePembayaran = {
  tunai: 'tunai',
  transfer: 'transfer',
  kartu_kredit: 'kartu_kredit',
  kartu_debit: 'kartu_debit',
  qris: 'qris',
} as const;
