/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { CreatePatientDtoJenisKelamin } from './createPatientDtoJenisKelamin';

export interface CreatePatientDto {
  /** Nama lengkap pasien */
  nama_lengkap: string;
  /** NIK 16 digit */
  nik?: string;
  email?: string;
  no_hp?: string;
  tanggal_lahir?: string;
  jenis_kelamin?: CreatePatientDtoJenisKelamin;
  alamat?: string;
  riwayat_alergi?: string;
  riwayat_penyakit?: string;
  catatan_khusus?: string;
}
