/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { CreatePaymentDtoMetodePembayaran } from './createPaymentDtoMetodePembayaran';
import type { CreatePaymentDtoStatusPembayaran } from './createPaymentDtoStatusPembayaran';

export interface CreatePaymentDto {
  /** ID Rekam Medis */
  medicalRecordId: number;
  /** ID Pasien */
  patientId: number;
  /** Tanggal pembayaran */
  tanggalPembayaran: string;
  /**
   * Total biaya sebelum diskon
   * @minimum 0
   */
  totalBiaya: number;
  /**
   * Total diskon
   * @minimum 0
   */
  diskonTotal?: number;
  /**
   * Jumlah yang dibayarkan
   * @minimum 0
   */
  jumlahBayar: number;
  /** Metode pembayaran */
  metodePembayaran: CreatePaymentDtoMetodePembayaran;
  /** Status pembayaran */
  statusPembayaran?: CreatePaymentDtoStatusPembayaran;
  /** Keterangan tambahan */
  keterangan?: string;
  /** ID user yang membuat */
  createdBy?: number;
}
