/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

/**
 * Status pembayaran
 */
export type CreatePaymentDtoStatusPembayaran = typeof CreatePaymentDtoStatusPembayaran[keyof typeof CreatePaymentDtoStatusPembayaran];


export const CreatePaymentDtoStatusPembayaran = {
  pending: 'pending',
  lunas: 'lunas',
  sebagian: 'sebagian',
  dibatalkan: 'dibatalkan',
} as const;
