/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export interface CreateTreatmentDto {
  /** ID kategori perawatan */
  categoryId: number;
  /**
   * Nama perawatan
   * @maxLength 250
   */
  namaPerawatan: string;
  /** Deskripsi detail perawatan */
  deskripsi?: string;
  /**
   * Harga perawatan dalam rupiah
   * @minimum 0
   */
  harga: number;
  /**
   * Estimasi durasi perawatan dalam menit
   * @minimum 0
   */
  durasiEstimasi?: number;
  /** Status aktif perawatan */
  isActive?: boolean;
}
