/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type CreatePatientDtoJenisKelamin = typeof CreatePatientDtoJenisKelamin[keyof typeof CreatePatientDtoJenisKelamin];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePatientDtoJenisKelamin = {
  L: 'L',
  P: 'P',
} as const;
