/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

/**
 * Status pembayaran
 */
export type CreatePaymentDtoStatusPembayaran = typeof CreatePaymentDtoStatusPembayaran[keyof typeof CreatePaymentDtoStatusPembayaran];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePaymentDtoStatusPembayaran = {
  pending: 'pending',
  lunas: 'lunas',
  sebagian: 'sebagian',
  dibatalkan: 'dibatalkan',
} as const;
