/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type MedicalRecordsControllerSearchAppointmentStatus = typeof MedicalRecordsControllerSearchAppointmentStatus[keyof typeof MedicalRecordsControllerSearchAppointmentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MedicalRecordsControllerSearchAppointmentStatus = {
  dijadwalkan: 'dijadwalkan',
  selesai: 'selesai',
  dibatalkan: 'dibatalkan',
} as const;
