/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type MedicalRecordsControllerFindAllAppointmentStatus = typeof MedicalRecordsControllerFindAllAppointmentStatus[keyof typeof MedicalRecordsControllerFindAllAppointmentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MedicalRecordsControllerFindAllAppointmentStatus = {
  dijadwalkan: 'dijadwalkan',
  selesai: 'selesai',
  dibatalkan: 'dibatalkan',
  menunggu_konfirmasi: 'menunggu_konfirmasi',
} as const;
