/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { MedicalRecordsControllerFindAllAppointmentStatus } from './medicalRecordsControllerFindAllAppointmentStatus';
import type { MedicalRecordsControllerFindAllSortOrder } from './medicalRecordsControllerFindAllSortOrder';

export type MedicalRecordsControllerFindAllParams = {
/**
 * Filter berdasarkan ID pasien
 */
patient_id?: string;
/**
 * Filter berdasarkan ID dokter
 */
doctor_id?: string;
/**
 * Filter berdasarkan ID appointment
 */
appointment_id?: string;
/**
 * Pencarian umum (berlaku untuk field SOAP: Subjective, Objective, Assessment, Plan)
 */
search?: string;
/**
 * Tanggal mulai untuk filter rekam medis
 */
start_date?: string;
/**
 * Tanggal akhir untuk filter rekam medis
 */
end_date?: string;
/**
 * Filter berdasarkan status appointment
 */
appointment_status?: MedicalRecordsControllerFindAllAppointmentStatus;
/**
 * Nomor halaman untuk pagination
 */
page?: number;
/**
 * Jumlah data per halaman
 */
limit?: number;
/**
 * Field untuk sorting
 */
sort_by?: string;
/**
 * Urutan sorting (ASC atau DESC)
 */
sort_order?: MedicalRecordsControllerFindAllSortOrder;
};
