/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type MedicalRecordsControllerSearchSortOrder = typeof MedicalRecordsControllerSearchSortOrder[keyof typeof MedicalRecordsControllerSearchSortOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MedicalRecordsControllerSearchSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
