/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { TreatmentDetailDto } from './treatmentDetailDto';

export interface MedicalRecordTreatmentResponseDto {
  /** ID Medical Record Treatment */
  id: number;
  /** ID Rekam Medis */
  medicalRecordId: number;
  /** ID Perawatan */
  treatmentId: number;
  /** Jumlah perawatan */
  jumlah: number;
  /** Harga satuan */
  hargaSatuan: number;
  /** Subtotal (jumlah x harga satuan) */
  subtotal: number;
  /** Diskon */
  diskon: number;
  /** Total (subtotal - diskon) */
  total: number;
  /** Keterangan */
  keterangan?: string;
  createdAt: string;
  updatedAt: string;
  treatment?: TreatmentDetailDto;
}
