/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { TreatmentSubsetDto } from './treatmentSubsetDto';

export interface MedicalRecordTreatmentSubsetDto {
  id: number;
  jumlah: number;
  price_snapshot: number;
  treatment?: TreatmentSubsetDto;
}
