/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type MedicalRecordTreatmentsControllerFindAllParams = {
/**
 * Filter berdasarkan Medical Record ID
 */
medicalRecordId?: number;
/**
 * Filter berdasarkan Treatment ID
 */
treatmentId?: number;
/**
 * Nomor halaman
 * @minimum 1
 */
page?: number;
/**
 * Jumlah data per halaman
 * @minimum 1
 */
limit?: number;
};
