/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { MedicalRecordTreatmentsControllerGetTotalByMedicalRecordId200Data } from './medicalRecordTreatmentsControllerGetTotalByMedicalRecordId200Data';

export type MedicalRecordTreatmentsControllerGetTotalByMedicalRecordId200 = {
  statusCode?: number;
  message?: string;
  data?: MedicalRecordTreatmentsControllerGetTotalByMedicalRecordId200Data;
};
