/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { MedicalRecordsControllerSearchAppointmentStatus } from './medicalRecordsControllerSearchAppointmentStatus';
import type { MedicalRecordsControllerSearchSortOrder } from './medicalRecordsControllerSearchSortOrder';

export type MedicalRecordsControllerSearchParams = {
/**
 * Filter berdasarkan ID pasien
 */
patient_id?: number;
/**
 * Filter berdasarkan ID dokter
 */
doctor_id?: number;
/**
 * Filter berdasarkan ID appointment
 */
appointment_id?: number;
/**
 * Pencarian umum (berlaku untuk field SOAP: Subjective, Objective, Assessment, Plan)
 */
search?: string;
/**
 * Tanggal mulai untuk filter rekam medis
 */
start_date?: string;
/**
 * Tanggal akhir untuk filter rekam medis
 */
end_date?: string;
/**
 * Filter berdasarkan status appointment
 */
appointment_status?: MedicalRecordsControllerSearchAppointmentStatus;
/**
 * Nomor halaman untuk pagination
 */
page?: number;
/**
 * Jumlah data per halaman
 */
limit?: number;
/**
 * Field untuk sorting
 */
sort_by?: string;
/**
 * Urutan sorting (ASC atau DESC)
 */
sort_order?: MedicalRecordsControllerSearchSortOrder;
};
