/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { NotificationPatientDto } from './notificationPatientDto';
import type { NotificationDoctorDto } from './notificationDoctorDto';

export interface NotificationAppointmentDto {
  id: number;
  /** Tanggal janji temu */
  tanggal_janji: string;
  /** Jam janji temu */
  jam_janji: string;
  patient?: NotificationPatientDto;
  doctor?: NotificationDoctorDto;
}
