/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

/**
 * Jenis notifikasi berdasarkan enum NotificationType
 */
export type NotificationTypeStatDtoType = typeof NotificationTypeStatDtoType[keyof typeof NotificationTypeStatDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationTypeStatDtoType = {
  email_reminder: 'email_reminder',
  sms_reminder: 'sms_reminder',
  whatsapp_confirmation: 'whatsapp_confirmation',
} as const;
