/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type NotificationsControllerRetryAllFailedParams = {
/**
 * Maksimal 50
 */
limit?: number;
};
