/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

/**
 * Jenis notifikasi (Email/WA)
 */
export type NotificationResponseDtoType = typeof NotificationResponseDtoType[keyof typeof NotificationResponseDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationResponseDtoType = {
  email_reminder: 'email_reminder',
  sms_reminder: 'sms_reminder',
  whatsapp_confirmation: 'whatsapp_confirmation',
} as const;
