/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { NotificationAppointmentDto } from './notificationAppointmentDto';
import type { NotificationResponseDtoStatus } from './notificationResponseDtoStatus';
import type { NotificationResponseDtoType } from './notificationResponseDtoType';

export interface NotificationResponseDto {
  id: string;
  appointment_id: string;
  /** Jenis notifikasi (Email/WA) */
  type: NotificationResponseDtoType;
  /** Status pengiriman */
  status: NotificationResponseDtoStatus;
  /** Waktu yang dijadwalkan untuk dikirim */
  send_at: string;
  /**
   * Waktu aktual terkirim (Null jika belum terkirim)
   * @nullable
   */
  sent_at?: string | null;
  created_at: string;
  updated_at: string;
  /** Detail appointment terkait notifikasi ini */
  appointment?: NotificationAppointmentDto;
}
