/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { NotificationTypeStatDtoType } from './notificationTypeStatDtoType';

export interface NotificationTypeStatDto {
  /** Jenis notifikasi berdasarkan enum NotificationType */
  type: NotificationTypeStatDtoType;
  /**
   * Jumlah notifikasi berdasarkan jenisnya
   * @minimum 0
   */
  count: number;
}
