/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { NotificationDoctorDto } from './notificationDoctorDto';
import type { NotificationPatientDto } from './notificationPatientDto';

export interface NotificationAppointmentDto {
  id: string;
  /** Tanggal janji temu */
  tanggal_janji: string;
  /** Jam janji temu */
  jam_janji: string;
  patient?: NotificationPatientDto;
  doctor?: NotificationDoctorDto;
}
