/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

/**
 * Status pengiriman
 */
export type NotificationResponseDtoStatus = typeof NotificationResponseDtoStatus[keyof typeof NotificationResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationResponseDtoStatus = {
  pending: 'pending',
  sent: 'sent',
  failed: 'failed',
} as const;
