/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { NotificationTypeStatDto } from './notificationTypeStatDto';

export interface NotificationStatsDto {
  /**
   * Total semua notifikasi
   * @minimum 0
   */
  total: number;
  /**
   * Jumlah notifikasi yang masih pending
   * @minimum 0
   */
  pending: number;
  /**
   * Jumlah notifikasi yang berhasil dikirim
   * @minimum 0
   */
  sent: number;
  /**
   * Jumlah notifikasi yang gagal dikirim
   * @minimum 0
   */
  failed: number;
  /**
   * Jumlah notifikasi yang dijadwalkan hari ini
   * @minimum 0
   */
  scheduled_today: number;
  /**
   * Jumlah notifikasi yang dijadwalkan minggu ini
   * @minimum 0
   */
  scheduled_this_week: number;
  /** Statistik notifikasi berdasarkan jenis notifikasi */
  by_type?: NotificationTypeStatDto[];
}
