/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type NotificationsControllerFindAllStatus = typeof NotificationsControllerFindAllStatus[keyof typeof NotificationsControllerFindAllStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationsControllerFindAllStatus = {
  pending: 'pending',
  sent: 'sent',
  failed: 'failed',
} as const;
