/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { NotificationsControllerFindAllStatus } from './notificationsControllerFindAllStatus';
import type { NotificationsControllerFindAllType } from './notificationsControllerFindAllType';

export type NotificationsControllerFindAllParams = {
/**
 * Filter status notifikasi
 */
status?: NotificationsControllerFindAllStatus;
/**
 * Filter jenis notifikasi
 */
type?: NotificationsControllerFindAllType;
/**
 * Halaman (default: 1)
 * @minimum 1
 */
page?: number;
/**
 * Jumlah per halaman (default: 20)
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
