/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { PaginationMetaDto } from './paginationMetaDto';
import type { TreatmentResponseDto } from './treatmentResponseDto';

export interface PaginatedTreatmentResponseDto {
  data: TreatmentResponseDto[];
  meta: PaginationMetaDto;
}
