/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { UserSummaryDto } from './userSummaryDto';

export interface PasswordChangeResponseDto {
  message: string;
  timestamp: string;
  user?: UserSummaryDto;
}
