/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type PatientsControllerFindByDoctorSortOrder = typeof PatientsControllerFindByDoctorSortOrder[keyof typeof PatientsControllerFindByDoctorSortOrder];


export const PatientsControllerFindByDoctorSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
