/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export interface PatientSubsetDto {
  id: number;
  nama_lengkap: string;
  no_rm: string;
  /** @nullable */
  tanggal_lahir?: string | null;
}
