/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type PatientsControllerFindByDoctorJenisKelamin = typeof PatientsControllerFindByDoctorJenisKelamin[keyof typeof PatientsControllerFindByDoctorJenisKelamin];


export const PatientsControllerFindByDoctorJenisKelamin = {
  L: 'L',
  P: 'P',
} as const;
