/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { PatientResponseDtoJenisKelamin } from './patientResponseDtoJenisKelamin';

export interface PatientResponseDto {
  /** ID unik pasien */
  id: number;
  /** Nomor rekam medis pasien */
  nomor_rekam_medis: string;
  /** Nomor Induk Kependudukan */
  nik: string;
  /** Nama lengkap pasien */
  nama_lengkap: string;
  /** Tanggal lahir pasien */
  tanggal_lahir: string;
  /** Umur pasien dalam tahun */
  umur: number;
  /** Jenis kelamin pasien */
  jenis_kelamin: PatientResponseDtoJenisKelamin;
  /** Email pasien */
  email: string;
  /** Nomor handphone pasien */
  no_hp: string;
  /** Alamat lengkap pasien */
  alamat: string;
  /** Riwayat alergi yang dimiliki pasien */
  riwayat_alergi: string;
  /** Riwayat penyakit pasien */
  riwayat_penyakit: string;
  /** Catatan medis khusus yang perlu diperhatikan */
  catatan_khusus: string;
  /** Golongan darah pasien */
  golongan_darah: string;
  /** Pekerjaan pasien */
  pekerjaan: string;
  /** Nama kontak darurat */
  kontak_darurat_nama: string;
  /** Nomor kontak darurat */
  kontak_darurat_nomor: string;
  /** Relasi kontak darurat dengan pasien */
  kontak_darurat_relasi: string;
  /** Status apakah pasien terdaftar online */
  is_registered_online: boolean;
  /** Status aktif pasien */
  is_active: boolean;
  /** Menandakan apakah pasien baru pertama kali mendaftar */
  is_new_patient: boolean;
  /** Tanggal dibuatnya data pasien */
  created_at: string;
  /** Tanggal terakhir data pasien diperbarui */
  updated_at: string;
}
