/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type PatientsControllerSearchJenisKelamin = typeof PatientsControllerSearchJenisKelamin[keyof typeof PatientsControllerSearchJenisKelamin];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatientsControllerSearchJenisKelamin = {
  L: 'L',
  P: 'P',
} as const;
