/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type PatientsControllerSearchSortOrder = typeof PatientsControllerSearchSortOrder[keyof typeof PatientsControllerSearchSortOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatientsControllerSearchSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
