/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { PatientsControllerFindAllSortBy } from './patientsControllerFindAllSortBy';
import type { PatientsControllerFindAllSortOrder } from './patientsControllerFindAllSortOrder';
import type { PatientsControllerFindAllJenisKelamin } from './patientsControllerFindAllJenisKelamin';

export type PatientsControllerFindAllParams = {
/**
 * Pencarian by nama, NIK, email, nomor rekam medis
 */
search?: string;
page?: number;
limit?: number;
sortBy?: PatientsControllerFindAllSortBy;
sortOrder?: PatientsControllerFindAllSortOrder;
jenis_kelamin?: PatientsControllerFindAllJenisKelamin;
umur_min?: number;
umur_max?: number;
tanggal_daftar_dari?: string;
tanggal_daftar_sampai?: string;
doctor_id?: number;
/**
 * Hanya pasien aktif
 */
is_active?: boolean;
/**
 * Hanya pasien baru (30 hari terakhir)
 */
is_new?: boolean;
};
