/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { PatientsControllerFindByDoctorSortBy } from './patientsControllerFindByDoctorSortBy';
import type { PatientsControllerFindByDoctorSortOrder } from './patientsControllerFindByDoctorSortOrder';
import type { PatientsControllerFindByDoctorJenisKelamin } from './patientsControllerFindByDoctorJenisKelamin';

export type PatientsControllerFindByDoctorParams = {
/**
 * Pencarian by nama, NIK, email, nomor rekam medis
 */
search?: string;
page?: number;
limit?: number;
sortBy?: PatientsControllerFindByDoctorSortBy;
sortOrder?: PatientsControllerFindByDoctorSortOrder;
jenis_kelamin?: PatientsControllerFindByDoctorJenisKelamin;
umur_min?: number;
umur_max?: number;
tanggal_daftar_dari?: string;
tanggal_daftar_sampai?: string;
doctor_id?: number;
/**
 * Hanya pasien aktif
 */
is_active?: boolean;
/**
 * Hanya pasien baru (30 hari terakhir)
 */
is_new?: boolean;
};
