/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

/**
 * Jenis kelamin pasien
 */
export type PatientResponseDtoJenisKelamin = typeof PatientResponseDtoJenisKelamin[keyof typeof PatientResponseDtoJenisKelamin];


export const PatientResponseDtoJenisKelamin = {
  L: 'L',
  P: 'P',
} as const;
