/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

/**
 * Jenis kelamin pasien
 */
export type PatientResponseDtoJenisKelamin = typeof PatientResponseDtoJenisKelamin[keyof typeof PatientResponseDtoJenisKelamin];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatientResponseDtoJenisKelamin = {
  L: 'L',
  P: 'P',
} as const;
