/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { PatientsControllerSearchSortBy } from './patientsControllerSearchSortBy';
import type { PatientsControllerSearchSortOrder } from './patientsControllerSearchSortOrder';
import type { PatientsControllerSearchJenisKelamin } from './patientsControllerSearchJenisKelamin';

export type PatientsControllerSearchParams = {
/**
 * Kata kunci pencarian
 */
search?: string;
page?: number;
limit?: number;
sortBy?: PatientsControllerSearchSortBy;
sortOrder?: PatientsControllerSearchSortOrder;
jenis_kelamin?: PatientsControllerSearchJenisKelamin;
umur_min?: number;
umur_max?: number;
tanggal_daftar_dari?: string;
tanggal_daftar_sampai?: string;
doctor_id?: number;
/**
 * Hanya pasien aktif
 */
is_active?: boolean;
/**
 * Hanya pasien baru (30 hari terakhir)
 */
is_new?: boolean;
has_allergies?: boolean;
};
