/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export interface PaymentResponseDto {
  /** ID Pembayaran */
  id: number;
  /** ID Rekam Medis */
  medicalRecordId: number;
  /** ID Pasien */
  patientId: number;
  /** Nomor Invoice */
  nomorInvoice: string;
  /** Tanggal Pembayaran */
  tanggalPembayaran: string;
  /** Total Biaya */
  totalBiaya: number;
  /** Total Diskon */
  diskonTotal: number;
  /** Total Akhir */
  totalAkhir: number;
  /** Jumlah yang Dibayar */
  jumlahBayar: number;
  /** Kembalian */
  kembalian: number;
  /** Metode Pembayaran */
  metodePembayaran: string;
  /** Status Pembayaran */
  statusPembayaran: string;
  /** Keterangan */
  keterangan?: string;
  /** ID Pembuat */
  createdBy?: number;
  /** Tanggal Dibuat */
  createdAt: string;
  /** Tanggal Diupdate */
  updatedAt: string;
}
