/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { PatientSubsetDto } from './patientSubsetDto';
import type { MedicalRecordSubsetDto } from './medicalRecordSubsetDto';

export interface PaymentResponseDto {
  /** ID Pembayaran */
  id: string;
  /** ID Rekam Medis */
  medicalRecordId: string;
  /** ID Pasien */
  patientId: string;
  /** Nomor Invoice */
  nomorInvoice: string;
  /** Tanggal Pembayaran */
  tanggalPembayaran: string;
  /** Total Biaya */
  totalBiaya: number;
  /** Total Diskon */
  diskonTotal: number;
  /** Total Akhir */
  totalAkhir: number;
  /** Jumlah yang Dibayar */
  jumlahBayar: number;
  /** Kembalian */
  kembalian: number;
  /** Metode Pembayaran */
  metodePembayaran: string;
  /** Status Pembayaran */
  statusPembayaran: string;
  /** Keterangan */
  keterangan?: string;
  /** ID Pembuat */
  createdBy?: string;
  /** Tanggal Dibuat */
  createdAt: string;
  /** Tanggal Diupdate */
  updatedAt: string;
  patient?: PatientSubsetDto;
  medicalRecord?: MedicalRecordSubsetDto;
}
