/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type PaymentsControllerGetRevenueByPeriodGroupBy = typeof PaymentsControllerGetRevenueByPeriodGroupBy[keyof typeof PaymentsControllerGetRevenueByPeriodGroupBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentsControllerGetRevenueByPeriodGroupBy = {
  day: 'day',
  month: 'month',
  year: 'year',
} as const;
