/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { PaymentsControllerGetRevenueByPeriodGroupBy } from './paymentsControllerGetRevenueByPeriodGroupBy';

export type PaymentsControllerGetRevenueByPeriodParams = {
startDate: string;
endDate: string;
groupBy?: PaymentsControllerGetRevenueByPeriodGroupBy;
};
