/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { PaymentsControllerFindAllStatusPembayaran } from './paymentsControllerFindAllStatusPembayaran';
import type { PaymentsControllerFindAllMetodePembayaran } from './paymentsControllerFindAllMetodePembayaran';

export type PaymentsControllerFindAllParams = {
/**
 * Filter berdasarkan Medical Record ID
 */
medicalRecordId?: number;
/**
 * Filter berdasarkan Patient ID
 */
patientId?: number;
/**
 * Filter berdasarkan status pembayaran
 */
statusPembayaran?: PaymentsControllerFindAllStatusPembayaran;
/**
 * Filter berdasarkan metode pembayaran
 */
metodePembayaran?: PaymentsControllerFindAllMetodePembayaran;
/**
 * Tanggal mulai (ISO format)
 */
startDate?: string;
/**
 * Tanggal akhir (ISO format)
 */
endDate?: string;
/**
 * Cari berdasarkan nomor invoice
 */
search?: string;
/**
 * Halaman
 * @minimum 1
 */
page?: number;
/**
 * Jumlah data per halaman
 * @minimum 1
 */
limit?: number;
};
