/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type PaymentsControllerFindAllMetodePembayaran = typeof PaymentsControllerFindAllMetodePembayaran[keyof typeof PaymentsControllerFindAllMetodePembayaran];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentsControllerFindAllMetodePembayaran = {
  tunai: 'tunai',
  transfer: 'transfer',
  kartu_kredit: 'kartu_kredit',
  kartu_debit: 'kartu_debit',
  qris: 'qris',
} as const;
