/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { ProcessPaymentDtoMetodePembayaran } from './processPaymentDtoMetodePembayaran';

export interface ProcessPaymentDto {
  /** Jumlah uang yang diserahkan pasien */
  jumlah_bayar: number;
  /** Metode pembayaran */
  metode_pembayaran: ProcessPaymentDtoMetodePembayaran;
  /** Catatan tambahan */
  keterangan?: string;
}
