/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export interface ResetPasswordWithTokenDto {
  /** Reset token dari verifikasi OTP */
  resetToken: string;
  /**
   * Password baru
   * @minLength 8
   */
  newPassword: string;
}
