/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { CategoryInfoDto } from './categoryInfoDto';

export interface TreatmentResponseDto {
  id: number;
  categoryId: number;
  kodePerawatan: string;
  namaPerawatan: string;
  deskripsi?: string;
  harga: number;
  durasiEstimasi?: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  category?: CategoryInfoDto;
}
