/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { TreatmentsControllerFindAllSortBy } from './treatmentsControllerFindAllSortBy';
import type { TreatmentsControllerFindAllSortOrder } from './treatmentsControllerFindAllSortOrder';

export type TreatmentsControllerFindAllParams = {
/**
 * Kata kunci pencarian untuk nama perawatan
 */
search?: string;
/**
 * Filter berdasarkan ID kategori
 */
categoryId?: number;
/**
 * Filter berdasarkan status aktif
 */
isActive?: boolean;
/**
 * Nomor halaman
 * @minimum 1
 */
page?: number;
/**
 * Jumlah data per halaman
 * @minimum 1
 */
limit?: number;
/**
 * Field untuk sorting
 */
sortBy?: TreatmentsControllerFindAllSortBy;
/**
 * Arah sorting
 */
sortOrder?: TreatmentsControllerFindAllSortOrder;
};
