/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

/**
 * Metode pembayaran
 */
export type UpdatePaymentDtoMetodePembayaran = typeof UpdatePaymentDtoMetodePembayaran[keyof typeof UpdatePaymentDtoMetodePembayaran];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePaymentDtoMetodePembayaran = {
  tunai: 'tunai',
  transfer: 'transfer',
  kartu_kredit: 'kartu_kredit',
  kartu_debit: 'kartu_debit',
  qris: 'qris',
} as const;
