/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserDto {
  /** Nama lengkap pengguna */
  nama_lengkap?: string;
  /** Username baru untuk login */
  username?: string;
  /** Daftar ID role pengguna */
  roles?: number[];
}
