/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export interface UpdateTreatmentCategoryDto {
  /**
   * Nama kategori perawatan
   * @minLength 3
   * @maxLength 100
   */
  namaKategori?: string;
  /** Deskripsi kategori perawatan */
  deskripsi?: string;
  /** Status aktif kategori */
  isActive?: boolean;
}
