/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { UpdatePaymentDtoMetodePembayaran } from './updatePaymentDtoMetodePembayaran';
import type { UpdatePaymentDtoStatusPembayaran } from './updatePaymentDtoStatusPembayaran';

export interface UpdatePaymentDto {
  /** Tanggal pembayaran */
  tanggalPembayaran?: string;
  /**
   * Total biaya sebelum diskon
   * @minimum 0
   */
  totalBiaya?: number;
  /**
   * Total diskon
   * @minimum 0
   */
  diskonTotal?: number;
  /**
   * Jumlah yang dibayarkan
   * @minimum 0
   */
  jumlahBayar?: number;
  /** Metode pembayaran */
  metodePembayaran?: UpdatePaymentDtoMetodePembayaran;
  /** Status pembayaran */
  statusPembayaran?: UpdatePaymentDtoStatusPembayaran;
  /** Keterangan tambahan */
  keterangan?: string;
}
