/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserDto {
  /** Nama lengkap pengguna */
  nama_lengkap?: string;
  /** Username baru untuk login */
  username?: string;
  /** Email pengguna */
  email?: string;
  /** Password baru (kosongkan jika tidak ingin mengubah) */
  password?: string;
  /** Daftar ID role pengguna */
  roles?: number[];
}
