/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

/**
 * Status pembayaran
 */
export type UpdatePaymentDtoStatusPembayaran = typeof UpdatePaymentDtoStatusPembayaran[keyof typeof UpdatePaymentDtoStatusPembayaran];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePaymentDtoStatusPembayaran = {
  pending: 'pending',
  lunas: 'lunas',
  sebagian: 'sebagian',
  dibatalkan: 'dibatalkan',
} as const;
