/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { UserRoleDto } from './userRoleDto';

export interface UserResponseDto {
  id: number;
  username: string;
  nama_lengkap: string;
  /** @nullable */
  email?: string | null;
  /** Daftar role user */
  roles: UserRoleDto[];
  created_at: string;
  updated_at: string;
  /** @nullable */
  profile_photo?: string | null;
}
