/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { UsersControllerFindAllRole } from './usersControllerFindAllRole';

export type UsersControllerFindAllParams = {
/**
 * Filter by role
 */
role?: UsersControllerFindAllRole;
/**
 * Cari nama atau username
 */
search?: string;
/**
 * Halaman (default: 1)
 */
page?: number;
/**
 * Jumlah per halaman (default: 10, max: 100)
 */
limit?: number;
/**
 * Filter by status aktif
 */
isActive?: boolean;
};
