/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export interface VerifyOTPDto {
  /** Email pengguna */
  email: string;
  /**
   * Kode OTP 6 digit
   * @minLength 6
   * @maxLength 6
   */
  otp: string;
}
