export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    PROFILE: '/auth/me',
    VERIFY: '/auth/verify', 
    FORGOT_PASSWORD: '/auth/forgot-password', 
    VERIFY_OTP: '/auth/verify-otp',
    RESET_PASSWORD: '/auth/reset-password', 
  },

  USERS: {
    BASE: '/users',
    BY_ID: (id: string) => `/users/${id}`,
    STATISTICS: '/users/statistics',
    RECENT: '/users/recent',
    CHECK_USERNAME: (username: string) => `/users/check-username/${username}`,
    CHANGE_PASSWORD: '/users/change-password',
    ADMIN_RESET_PASSWORD: (id: string) => `/users/${id}/reset-password`,
    GENERATE_TEMP_PASSWORD: (id: string) => `/users/${id}/generate-temp-password`,
    ACTIVATION: {
      CHECK_STATUS: '/users/activation/check-status',
      REQUEST: '/users/activation/request',
      RESEND: '/users/activation/resend',
      VERIFY_TOKEN: '/users/activation/verify-token',
      ACTIVATE: '/users/activation/activate',
    },
  },

  PATIENTS: {
    BASE: '/patients',
    BY_ID: (id: string) => `/patients/${id}`,
    SEARCH: '/patients/search',
    STATISTICS: '/patients/statistics',
    BY_MR: (string: string) => `/patients/by-medical-record/${string}`,
    BY_NIK: (nik: string) => `/patients/by-nik/${nik}`,
    BY_DOCTOR: (doctorId: string) => `/patients/by-doctor/${doctorId}`,
    ACTIVATE: (id: string) => `/patients/${id}/activate`,
    RESTORE: (id: string) => `/patients/${id}/restore`,
  },

  APPOINTMENTS: {
    BASE: '/appointments',
    BY_ID: (id: string) => `/appointments/${id}`,
    COMPLETE: (id: string) => `/appointments/${id}/complete`,
    CANCEL: (id: string) => `/appointments/${id}/cancel`,
    PUBLIC: {
      DOCTORS: '/public/appointments/doctors',
      BOOK: '/public/appointments/book',
    },
  },

  MEDICAL_RECORDS: {
    BASE: '/medical-records',
    BY_ID: (id: string) => `/medical-records/${id}`, 
    SEARCH: '/medical-records/search',
    BY_APPOINTMENT: (id: string) => `/medical-records/by-appointment/${id}`, 
    DOCTOR_STATS: '/medical-records/stats/doctors',
    RESTORE: (id: string) => `/medical-records/${id}/restore`,
    HARD_DELETE: (id: string) => `/medical-records/${id}/permanent`,
  },

  TREATMENTS: {
    BASE: '/treatments',
    BY_ID: (id: string) => `/treatments/${id}`, 
    BY_CODE: (code: string) => `/treatments/kode/${code}`,
    ACTIVATE: (id: string) => `/treatments/${id}/activate`,
    DEACTIVATE: (id: string) => `/treatments/${id}/deactivate`, 
    RESTORE: (id: string) => `/treatments/${id}/restore`,
    CATEGORIES: {
      BASE: '/treatment-categories',
      BY_ID: (id: string) => `/treatment-categories/${id}`,
      RESTORE: (id: string) => `/treatment-categories/${id}/restore`,
    },
  },

  MR_TREATMENTS: {
    BASE: '/medical-record-treatments',
    BY_ID: (id: string) => `/medical-record-treatments/${id}`, 
    TOP_STATS: '/medical-record-treatments/stats/top-treatments',
    BY_MR_ID: (mrId: string) => `/medical-record-treatments/medical-record/${mrId}`,
    TOTAL_BY_MR_ID: (mrId: string) => `/medical-record-treatments/medical-record/${mrId}/total`, 
  },

  PAYMENTS: {
    BASE: '/payments',
    BY_ID: (id: string) => `/payments/${id}`,
    PROCESS: (id: string) => `/payments/${id}/process`, 
    CANCEL: (id: string) => `/payments/${id}/cancel`, 
    BY_INVOICE: (inv: string) => `/payments/invoice/${inv}`,
    BY_MR: (mrId: string) => `/payments/medical-record/${mrId}`,
    BY_PATIENT: (patientId: string) => `/payments/patient/${patientId}`, 
    STATISTICS: '/payments/statistics', 
    REVENUE: '/payments/revenue',
    REVENUE_PERIOD: '/payments/revenue/period',
  },

  NOTIFICATIONS: {
    BASE: '/notifications',
  },

  ROLES: {
    BASE: '/roles',
    BY_ID: (id: string) => `/roles/${id}`,
  },

  UPLOADS: {
    PROFILE_PHOTO: '/uploads/profile-photo',
  },
  HEALTH: {
    BASE: '/health',
    DETAILS: '/health/details', 
    LIVE: '/health/live', 
    READY: '/health/ready',
  },
} as const;

export const API_METHODS = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  PATCH: 'PATCH',
  DELETE: 'DELETE',
} as const;

export const HTTP_STATUS = {

  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  PROCESSING: 102,
  EARLY_HINTS: 103,

  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTI_STATUS: 207,
  ALREADY_REPORTED: 208,
  IM_USED: 226,

  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,

  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,

  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
} as const;