/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { AppointmentsControllerFindAllStatus } from './appointmentsControllerFindAllStatus';

export type AppointmentsControllerFindAllParams = {
/**
 * Items per page
 */
limit?: number;
/**
 * Page number
 */
page?: number;
status?: AppointmentsControllerFindAllStatus;
/**
 * Filter by Date (YYYY-MM-DD)
 */
date?: string;
/**
 * Filter by Doctor ID
 */
doctorId?: number;
};
