/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { AppointmentSubsetDtoStatus } from './appointmentSubsetDtoStatus';
import type { PatientSubsetDto } from './patientSubsetDto';

export interface AppointmentSubsetDto {
  id: string;
  appointment_date: string;
  status: AppointmentSubsetDtoStatus;
  patient?: PatientSubsetDto;
}
