/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export interface CreateUserDto {
  /** Nama lengkap pengguna */
  nama_lengkap: string;
  /** Username unik untuk login */
  username: string;
  /** Password pengguna, minimal 8 karakter */
  password: string;
  /** Email pengguna */
  email?: string;
  /** Daftar ID role yang dimiliki user */
  roles: number[];
}
