/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export interface CreateMedicalRecordDto {
  /** ID dari appointment yang terkait dengan rekam medis */
  appointment_id: string;
  /** ID user staff (perawat/dokter) yang membuat rekam medis */
  user_id_staff: string;
  /**
   * Bagian Subjektif dari SOAP (keluhan pasien)
   * @maxLength 5000
   */
  subjektif?: string;
  /**
   * Bagian Objektif dari SOAP (hasil pemeriksaan fisik/lab)
   * @maxLength 5000
   */
  objektif?: string;
  /**
   * Bagian Assessment dari SOAP (diagnosis)
   * @maxLength 5000
   */
  assessment?: string;
  /**
   * Bagian Plan dari SOAP (rencana terapi & tindak lanjut)
   * @maxLength 5000
   */
  plan?: string;
}
