/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { CreatePatientDtoJenisKelamin } from './createPatientDtoJenisKelamin';

export interface CreatePatientDto {
  /** Nama lengkap pasien */
  nama_lengkap: string;
  /** NIK 16 digit */
  nik?: string;
  email?: string;
  no_hp?: string;
  /** Tanggal Lahir (YYYY-MM-DD) */
  tanggal_lahir: string;
  jenis_kelamin?: CreatePatientDtoJenisKelamin;
  alamat?: string;
}
