/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type MedicalRecordsControllerSearchSortOrder = typeof MedicalRecordsControllerSearchSortOrder[keyof typeof MedicalRecordsControllerSearchSortOrder];


export const MedicalRecordsControllerSearchSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
