/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { AppointmentResponseDto } from './appointmentResponseDto';

export interface PaginatedAppointmentResponseDto {
  data: AppointmentResponseDto[];
  /** Total data keseluruhan */
  count: number;
  /** Halaman saat ini */
  page: number;
  /** Jumlah data per halaman */
  limit: number;
  /** Total halaman tersedia */
  totalPages: number;
}
