/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { PublicBookingDtoJenisKelamin } from './publicBookingDtoJenisKelamin';

export interface PublicBookingDto {
  /** Nama lengkap pasien */
  nama_lengkap: string;
  /** NIK 16 Digit */
  nik: string;
  /** Tanggal Lahir (YYYY-MM-DD) */
  tanggal_lahir: string;
  /** Nomor HP (WhatsApp) */
  no_hp: string;
  jenis_kelamin: PublicBookingDtoJenisKelamin;
  /** Alamat domisili */
  alamat: string;
  /** Email (Opsional) */
  email?: string;
  /** ID Dokter yang dipilih */
  doctor_id: string;
  /** Tanggal Janji (YYYY-MM-DD) */
  tanggal_janji: string;
  /** Jam Janji (HH:mm) */
  jam_janji: string;
  /** Keluhan utama */
  keluhan: string;
}
