/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type TreatmentCategoriesControllerFindAllParams = {
/**
 * Search keyword untuk nama atau deskripsi
 */
search?: string;
/**
 * Filter berdasarkan status aktif
 */
isActive?: boolean;
/**
 * Nomor halaman
 * @minimum 1
 */
page?: number;
/**
 * Jumlah item per halaman
 * @minimum 1
 */
limit?: number;
};
