/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export interface TreatmentCategoryResponseDto {
  /** ID kategori */
  id: string;
  /** Nama kategori */
  namaKategori: string;
  /**
   * Deskripsi kategori
   * @nullable
   */
  deskripsi: string | null;
  /** Status aktif */
  isActive: boolean;
  /** Tanggal dibuat */
  createdAt: string;
  /** Tanggal diupdate */
  updatedAt: string;
}
