/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */

export type TreatmentsControllerFindAllSortBy = typeof TreatmentsControllerFindAllSortBy[keyof typeof TreatmentsControllerFindAllSortBy];


export const TreatmentsControllerFindAllSortBy = {
  namaPerawatan: 'namaPerawatan',
  harga: 'harga',
  createdAt: 'createdAt',
  kodePerawatan: 'kodePerawatan',
} as const;
