/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Dentizy API
 * API Documentation untuk Sistem Manajemen Klinik Gigi
 * OpenAPI spec version: 1.0
 */
import type { UserResponseDtoDeletedAt } from './userResponseDtoDeletedAt';
import type { UserResponseDtoProfilePhoto } from './userResponseDtoProfilePhoto';
import type { UserRoleDto } from './userRoleDto';

export interface UserResponseDto {
  id: string;
  username: string;
  nama_lengkap: string;
  /** @nullable */
  email?: string | null;
  /** Daftar role user */
  roles: UserRoleDto[];
  created_at: string;
  updated_at: string;
  /** @nullable */
  deleted_at?: UserResponseDtoDeletedAt;
  /** Status aktif user */
  is_active: boolean;
  /** @nullable */
  profile_photo?: UserResponseDtoProfilePhoto;
}
