// frontend/src/core/constants/routes.constants.ts
export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    DASHBOARD: '/dashboard',
    APPOINTMENTS: '/appointments',
    APPOINTMENT_CREATE: '/appointments/new',
    APPOINTMENT_DETAIL: (id: number | string) => `/appointments/${id}`,
    APPOINTMENT_EDIT: (id: number | string) => `/appointments/${id}/edit`,
    PATIENTS: '/patients',
    PATIENT_CREATE: '/patients/new',
    PATIENT_DETAIL: (id: number | string) => `/patients/${id}`,
    PATIENT_EDIT: (id: number | string) => `/patients/${id}/edit`,
    MEDICAL_RECORDS: '/medical-records',
    MEDICAL_RECORD_CREATE: '/medical-records/new',
    MEDICAL_RECORD_DETAIL: (id: number | string) => `/medical-records/${id}`,
    MEDICAL_RECORD_EDIT: (id: number | string) => `/medical-records/${id}/edit`,
    USERS: '/users',
    USER_CREATE: '/users/new',
    USER_DETAIL: (id: number | string) => `/users/${id}`,
    USER_EDIT: (id: number | string) => `/users/${id}/edit`,
    REPORTS: '/reports',
    REPORT_APPOINTMENTS: '/reports/appointments',
    REPORT_PATIENTS: '/reports/patients',
    REPORT_MEDICAL_RECORDS: '/reports/medical-records',
    PAYMENTS: '/payments',
    PROFILE: '/profile',
    SETTINGS: '/settings',
    SETTINGS_NOTIFICATIONS: '/settings/notifications',
    TREATMENTS: '/treatments',
    NOT_FOUND: '/404',
    FORBIDDEN: '/403',
    SERVER_ERROR: '/500',
} as const;

export const PUBLIC_ROUTES = [ROUTES.HOME, ROUTES.LOGIN] as const;

export const PROTECTED_ROUTES = [
    ROUTES.DASHBOARD,
    ROUTES.APPOINTMENTS,
    ROUTES.PATIENTS,
    ROUTES.MEDICAL_RECORDS,
    ROUTES.USERS,
    ROUTES.REPORTS,
    ROUTES.PROFILE,
    ROUTES.SETTINGS,
] as const;